baseurl: "/" 

collections:
  artists:
    output: true

defaults:
  - scope:
      path: ""
      type: "artists"
    values:
      layout: "artist"
  - scope:
      path: ""
    values:
      layout: "default"